"""empty message

Revision ID: 032c55508422
Revises: 
Create Date: 2023-05-26 18:58:38.600766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '032c55508422'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shard',
    sa.Column('id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('name', sa.VARCHAR(length=10), nullable=True),
    sa.Column('tooltip', sa.VARCHAR(length=100), nullable=True),
    sa.Column('shortDesc', sa.VARCHAR(length=200), nullable=True),
    sa.Column('longDesc', sa.VARCHAR(length=200), nullable=True),
    sa.Column('iconPath', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('summoner',
    sa.Column('puuid', sa.VARCHAR(length=100), nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('icon_id', sa.VARCHAR(length=20), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('puuid')
    )
    op.create_table('version',
    sa.Column('id', sa.VARCHAR(length=10), nullable=False),
    sa.Column('version', sa.VARCHAR(length=10), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('num1', sa.Integer(), nullable=True),
    sa.Column('num2', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('champion',
    sa.Column('id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('version_id', sa.VARCHAR(length=20), nullable=True),
    sa.Column('key', sa.Integer(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('version_id', sa.VARCHAR(length=20), nullable=True),
    sa.Column('key', sa.Integer(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=150), nullable=True),
    sa.Column('info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match',
    sa.Column('id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('gameVersion', sa.VARCHAR(length=30), nullable=True),
    sa.Column('version_id', sa.VARCHAR(length=20), nullable=True),
    sa.Column('gameStartTimeStamp', sa.BIGINT(), nullable=True),
    sa.Column('gameDuration', sa.Integer(), nullable=True),
    sa.Column('winTeam', sa.Integer(), nullable=True),
    sa.Column('fisrtBloodTeam', sa.Integer(), nullable=True),
    sa.Column('firstTowerTeam', sa.Integer(), nullable=True),
    sa.Column('firstInhibitorTeam', sa.Integer(), nullable=True),
    sa.Column('isEarlySurrendered', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perk_style',
    sa.Column('id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('version_id', sa.VARCHAR(length=20), nullable=True),
    sa.Column('key', sa.Integer(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spell',
    sa.Column('id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('key', sa.Integer(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('version_id', sa.VARCHAR(length=20), nullable=True),
    sa.Column('info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perk',
    sa.Column('id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('perkStyle_id', sa.VARCHAR(length=20), nullable=True),
    sa.Column('version_id', sa.VARCHAR(length=20), nullable=True),
    sa.Column('key', sa.Integer(), nullable=True),
    sa.Column('slot', sa.Integer(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('shortDesc', sa.Text(), nullable=True),
    sa.Column('longDesc', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['perkStyle_id'], ['perk_style.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_detail',
    sa.Column('id', sa.VARCHAR(length=30), nullable=False),
    sa.Column('match_id', sa.VARCHAR(length=20), nullable=True),
    sa.Column('puuid', sa.VARCHAR(length=100), nullable=True),
    sa.Column('participantId', sa.Integer(), nullable=True),
    sa.Column('champion_id', sa.VARCHAR(length=20), nullable=True),
    sa.Column('isWin', sa.Boolean(), nullable=True),
    sa.Column('kills', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('champLevel', sa.Integer(), nullable=True),
    sa.Column('goldEarend', sa.Integer(), nullable=True),
    sa.Column('goldSpent', sa.Integer(), nullable=True),
    sa.Column('item0_id', sa.VARCHAR(length=20), nullable=True),
    sa.Column('item1_id', sa.VARCHAR(length=20), nullable=True),
    sa.Column('item2_id', sa.VARCHAR(length=20), nullable=True),
    sa.Column('item3_id', sa.VARCHAR(length=20), nullable=True),
    sa.Column('item4_id', sa.VARCHAR(length=20), nullable=True),
    sa.Column('item5_id', sa.VARCHAR(length=20), nullable=True),
    sa.Column('item6_id', sa.VARCHAR(length=20), nullable=True),
    sa.Column('itemsPurchased', sa.Integer(), nullable=True),
    sa.Column('longestTimeSpentLiving', sa.Integer(), nullable=True),
    sa.Column('shardDefense_id', sa.VARCHAR(length=20), nullable=True),
    sa.Column('shardFlex_id', sa.VARCHAR(length=20), nullable=True),
    sa.Column('shardOffense_id', sa.VARCHAR(length=20), nullable=True),
    sa.Column('mainPerkStyle_id', sa.VARCHAR(length=20), nullable=True),
    sa.Column('mainPerk1_id', sa.VARCHAR(length=20), nullable=True),
    sa.Column('mainPerk1Var1', sa.Integer(), nullable=True),
    sa.Column('mainPerk1Var2', sa.Integer(), nullable=True),
    sa.Column('mainPerk1Var3', sa.Integer(), nullable=True),
    sa.Column('mainPerk2_id', sa.VARCHAR(length=20), nullable=True),
    sa.Column('mainPerk2Var1', sa.Integer(), nullable=True),
    sa.Column('mainPerk2Var2', sa.Integer(), nullable=True),
    sa.Column('mainPerk2Var3', sa.Integer(), nullable=True),
    sa.Column('mainPerk3_id', sa.VARCHAR(length=20), nullable=True),
    sa.Column('mainPerk3Var1', sa.Integer(), nullable=True),
    sa.Column('mainPerk3Var2', sa.Integer(), nullable=True),
    sa.Column('mainPerk3Var3', sa.Integer(), nullable=True),
    sa.Column('mainPerk4_id', sa.VARCHAR(length=20), nullable=True),
    sa.Column('mainPerk4Var1', sa.Integer(), nullable=True),
    sa.Column('mainPerk4Var2', sa.Integer(), nullable=True),
    sa.Column('mainPerk4Var3', sa.Integer(), nullable=True),
    sa.Column('subPerkStyle_id', sa.VARCHAR(length=20), nullable=True),
    sa.Column('subPerk1_id', sa.VARCHAR(length=20), nullable=True),
    sa.Column('subPerk1Var1', sa.Integer(), nullable=True),
    sa.Column('subPerk1Var2', sa.Integer(), nullable=True),
    sa.Column('subPerk1Var3', sa.Integer(), nullable=True),
    sa.Column('subPerk2_id', sa.VARCHAR(length=20), nullable=True),
    sa.Column('subPerk2Var1', sa.Integer(), nullable=True),
    sa.Column('subPerk2Var2', sa.Integer(), nullable=True),
    sa.Column('subPerk2Var3', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['champion_id'], ['champion.id'], ),
    sa.ForeignKeyConstraint(['item0_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['item1_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['item2_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['item3_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['item4_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['item5_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['item6_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['mainPerk1_id'], ['perk.id'], ),
    sa.ForeignKeyConstraint(['mainPerk2_id'], ['perk.id'], ),
    sa.ForeignKeyConstraint(['mainPerk3_id'], ['perk.id'], ),
    sa.ForeignKeyConstraint(['mainPerk4_id'], ['perk.id'], ),
    sa.ForeignKeyConstraint(['mainPerkStyle_id'], ['perk_style.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['puuid'], ['summoner.puuid'], ),
    sa.ForeignKeyConstraint(['shardDefense_id'], ['shard.id'], ),
    sa.ForeignKeyConstraint(['shardFlex_id'], ['shard.id'], ),
    sa.ForeignKeyConstraint(['shardOffense_id'], ['shard.id'], ),
    sa.ForeignKeyConstraint(['subPerk1_id'], ['perk.id'], ),
    sa.ForeignKeyConstraint(['subPerk2_id'], ['perk.id'], ),
    sa.ForeignKeyConstraint(['subPerkStyle_id'], ['perk_style.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_detail')
    op.drop_table('perk')
    op.drop_table('spell')
    op.drop_table('perk_style')
    op.drop_table('match')
    op.drop_table('item')
    op.drop_table('champion')
    op.drop_table('version')
    op.drop_table('summoner')
    op.drop_table('shard')
    # ### end Alembic commands ###
